apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: appsso-starter-java-sso-client
  annotations:
    kapp.k14s.io/identity: v1;canary/carto.run/Workload/appsso-starter-java;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"appsso-starter-java","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1667248713819291429","kapp.k14s.io/association":"v1.62dd05773dee8bbc22469c31a68bbe08"},"name":"appsso-starter-java","namespace":"canary"},"spec":{"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"gitops_repository_name","value":"trp-gitops-canary"}],"serviceClaims":[{"name":"sso-client","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"appsso-starter-java"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/tanzu-end-to-end/trp-appsso-starter-java"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1667248713819291429"
    kapp.k14s.io/association: v1.62dd05773dee8bbc22469c31a68bbe08
    app.kubernetes.io/component: run
    carto.run/workload-name: appsso-starter-java
spec:
  name: sso-client
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: appsso-starter-java
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: appsso-starter-java

